platform :ios, '9.0'

target 'Lab3Make24' do
  use_frameworks!
        pod 'NotificationBannerSwift'

  target 'Lab3Make24Tests' do
    #inherit! :search_paths
        pod 'NotificationBannerSwift'
  end

end
